In [4]:
import numpy as ny
x=ny.array([[1,2,3,4],[5,6,7,8]])
print(x[1,1:4])

[6 7 8]


In [5]:
import numpy as ny
x=ny.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x[1,2])

7


In [6]:
import numpy as ny
x=ny.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
row_slice=x[0:2,:]
print(row_slice)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
import numpy as ny
x=ny.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
row_slice=x[:,1:3]
print(row_slice)

[[ 2  3]
 [ 6  7]
 [10 11]]


In [15]:
#numpy
import numpy as ny
x=ny.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [16]:
#0 d array
import numpy as ny
x=ny.array(5)
print(x)

5


In [17]:
#1 d array
import numpy as ny
x=ny.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [19]:
#2 d array : m,ade up0 of two 1 d array
import numpy as ny
x=ny.array([[1,2,3],[6,4,5]])
print(x)

[[1 2 3]
 [6 4 5]]


In [20]:
#3 d array 
#made up of two 2d array
import numpy as ny
x=ny.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(x)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
#dimensio0ns: syntax=ndim : tells how many dimensiuons a array has
import numpy as ny
x=ny.array(5)
y=ny.array([1,2,3,4,5])
z=ny.array([[1,2,3],[6,4,5]])
w=ny.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(x.ndim)
print(y.ndim)
print(z.ndim)
print(w.ndim)

0
1
2
3


In [25]:
#accessing array elements
import numpy as ny
y=ny.array([1,2,3,4,5])
w=ny.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(y[4])
print(w[1])
print(w[1][1])
print(w[1][1][1])

5
[[5 6]
 [7 8]]
[7 8]
8


In [26]:
#addition of array
import numpy as ny
y=ny.array([1,2,3,4,5])
print(y[2]+y[4])

8


In [27]:
import numpy as ny
w=ny.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(w[1][1][1]+w[0][1][1])

12


In [29]:
#accessing 2d array
import numpy as ny
z=ny.array([[1,2,3],[6,4,5]])
print("second element of first row",
      z[0][1])

second element of first row 2


In [30]:
#slicing operation
import numpy as ny
y=ny.array([1,2,3,4,5])
print(y[1:4])

[2 3 4]


In [31]:
import numpy as ny
y=ny.array([1,2,3,4,5])
print(y[:])

[1 2 3 4 5]


In [32]:
#negative slicing
import numpy as ny
y=ny.array([1,2,3,4,5])
print(y[-4:-1])

[2 3 4]


In [33]:
#
import numpy as ny
y=ny.array([1,2,3,4,5])
print(y[1:4:2])

[2 4]


In [2]:
#Q3
import numpy as ny
list=[11,12,13,14,15]
arr=ny.array(list)
print(arr)

[11 12 13 14 15]


In [3]:
#Q2
import numpy as np
arr=np.linspace(5,50,10)
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [5]:
#4
import numpy as np
arr=np.array([11,12,13,14,15])
reverse=arr[::-1]
print(reverse)

[15 14 13 12 11]


In [6]:
#7
import numpy as np
arr=np.array([[1,2,3,4],[10,11,12,13],[200,300,400,500],[15,16,17,18]])
print(arr[:2,:2])

[[ 1  2]
 [10 11]]


In [8]:
#8
import numpy as np
a=np.array([0,1,2,3])
b=np.array([10,20,30,40])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[10 21 32 43]
[-10 -19 -28 -37]
[  0  20  60 120]
[0.         0.05       0.06666667 0.075     ]
